services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tracker
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
  analytics:
    image: metabase/metabase
    ports:
      - "3000:3000"