services:
  db:
    image: citusdata/citus:13.0.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tracker
    volumes:
      - ./sql/init:/docker-entrypoint-initdb.d
  analytics:
    image: metabase/metabase
    ports:
      - "3000:3000"